### ISSUE TITLE
Thought this might belong here:

### ISSUE THREAD

**Issue by claytonjhamilton** [vilijajoyce/git-resources#1]
https://rogerdudler.github.io/git-guide/
*I appreciated this high-level orientation as a starting point!

I've also created a presentation explaining how to use git internally within VA. Happy to send you a copy if you'd like. Reach me anytime at clayton.hamilton@va.gov.

Best,
Clayton

**Comment by vilijajoyce** [comment]
@claytonjhamilton Thank you so much for this helpful link. I'd also appreciate a copy of your presentation. I'll follow-up by email. Take care.
